### ISSUE TITLE
Allow Server to pull differential files when committed to Maps.

### ISSUE THREAD

**Issue by benrobson** [Warzone/TGM#676]
**Describe the feature you'd like**
> A clear description of the feature you feel should be implemented.

The server should listen to GitHub commits and if a new commit is committed, the Server should redownload the differential files.

**Usefulness of the feature**
> Include possible scenarios or situations where this feature would be useful.

This would provide a more autonomous way for the Server to update rotations and bring in map fixes and adding and deleting maps. Using GitHub and an API token for the username.

```
github:
  auth: false
  username: username
  token: your token # https://github.com/settings/tokens
```
